### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by jabarihunt** [EFTEC/UsagiMQ#1]
If we want to contribute to this project are there any specific instructions/comments/rules?  May plan is to...

1) Fork the project
2) Create a new branch off of master
3) Make my commits to the new branch
4) Create a pull request

**Comment by jorgecc** [comment]
You are free to go and decide. This is the reason why i published with license MIT.

Also, if you want to collaborate, you can join in it.  However, this project is really niche.    There are a lot of Message Queue servers, and most are for free. However, i created it because i don't want to spend time configuring and maintaining a MQ, so its fine for
a) people that use PHP
b) people that needs a easy and cheap MQ.
c) people don't want to mess with another MQ and/or with Java.

I have in mind a more interesting project than this, this project is just a toy.
